temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
hpc <- read.csv(unz(temp, "household_power_consumption.txt"), sep=";")
unlink(temp)
hpc1 <- filter(hpc, Date == "1/2/2007")
hpc2 <- filter(hpc, Date == "2/2/2007")
remove(hpc)
hpc3 <- rbind(hpc1, hpc2)
hpc3$Global_active_power <- as.numeric(hpc3$Global_active_power)
hpc3 <- transform(hpc3, cDate=as.Date(strptime(as.character(Date), format="%e/%m/%Y")))
hpc3 <- transform(hpc3, datetime=as.POSIXct(paste(as.character(hpc3$cDate), as.character(hpc3$Time)), "%Y-%m-%d %H:%M:%S"))
hpc3$Sub_metering_1 <- as.double(as.character(hpc3$Sub_metering_1))
hpc3$Sub_metering_2 <- as.double(as.character(hpc3$Sub_metering_2))
hpc3$Voltage <- as.double(as.character(hpc3$Voltage))
hpc3$Global_reactive_power <- as.double(as.character(hpc3$Global_reactive_power))
