source("load.R")
png(file="figure/plot4.png")
par(mfrow=c(2,2))
plot(hpc3$datetime, hpc3$Global_active_power/1000, type="n", xlab="", ylab="Global Active Power (kilowatts)")
lines(hpc3$datetime, hpc3$Global_active_power/1000)
plot(hpc3$datetime, hpc3$Voltage, type="n", xlab="datetime", ylab="Voltage")
lines(hpc3$datetime, hpc3$Voltage)
plot(hpc3$datetime, hpc3$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(hpc3$datetime, hpc3$Sub_metering_1)
lines(hpc3$datetime, hpc3$Sub_metering_2, col="red")
lines(hpc3$datetime, hpc3$Sub_metering_3, col="blue")
legend("topright", lwd=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(hpc3$datetime, hpc3$Global_reactive_power, type="n", xlab="datetime", ylab="Global_reactive_power")
lines(hpc3$datetime, hpc3$Global_reactive_power)
dev.off()